#!/bin/dash
# outputs error if an argument is provided
if (test $# != 0)
then
    echo "usage: girt-init"
    exit 1
elif (test -d .girt)
then
    # outputs error if .girt directory has already been created
    echo "girt-init: error: .girt already exists"
    exit 1
fi
# initialise all files used in girt
mkdir .girt
mkdir .girt/index
mkdir .girt/repository
mkdir .girt/commitPath
mkdir .girt/branch
mkdir .girt/branch/master
echo -n "" > .girt/message.txt
echo "master" > .girt/branchname.txt
echo -n "" > .girt/branch/master/message.txt
echo "Initialized empty girt repository in .girt"