#!/bin/dash
if (test -z "$(cat .girt/message.txt)") 
then
    echo "girt-branch: error: this command can not be run until after the first commit"
    exit 1
fi
if (test $# -eq 0)
then
    ls -d .girt/branch/* | sed -e "s/.girt\/branch\///g"
    exit
elif (test $# -eq 1)
then
    if (test $1 = '-d')
    then
        echo "girt-branch: error: branch name required"
        exit
    fi
    if (test -d .girt/branch/$1)
    then
        echo "girt-branch: error: branch '$1' already exists"
        exit
    fi
    mkdir .girt/branch/$1
    mkdir .girt/branch/$1/.girt
    mkdir .girt/branch/$1/.girt/index
    mkdir .girt/branch/$1/.girt/repository
    find . -maxdepth 1 -type f ! -name "girt-*" -a ! -name "test*.sh" -a ! -name "diary.txt" -exec cp -t .girt/branch/$1 {} +
    cp -r .girt/index/ .girt/branch/$1/.girt/index
    cp -r .girt/repository/ .girt/branch/$1/.girt/repository
    cp .girt/message.txt .girt/branch/$1/.girt/message.txt
elif (test $# -eq 2 && test $1 = '-d')
then
    if (test $2 = 'master')
    then
        echo "girt-branch: error: can not delete branch 'master'"
        exit
    elif (test -d .girt/branch/$2)
    then
        rm -r .girt/branch/$2
        echo "Deleted branch '$2'"
        exit
    fi
    echo "girt-branch: error: branch '$2' doesn't exist"
else
    echo "usage: girt-branch [-d] <branch>"
fi
