#!/bin/dash
for files in $@
do
    if (test -f $files) 
    then
        if (! cp $files .girt/index/$files) > /dev/null 2>&1
        then
            echo "girt-add: error: girt repository directory .girt not found"
            exit 1
        fi
    elif (test -f .girt/index/$files)
    then
        rm .girt/index/$files
    else
        echo "girt-add: error: can not open '$files'"
        exit 1
    fi
done