#!/bin/dash
# outputs error message if .girt was not initiated
if (! test -d .girt)
then
    echo "girt-status: error: girt repository directory .girt not found"
    exit 1
fi
# create file where output is stored
echo -n "" >.girt/status.txt
count=$(cat .girt/message.txt | cut -d " " -f1 | tail -n 1)
# get status of all files in current directory
for files in `ls`
do
    if (! test -f .girt/index/$files)
    then
        echo "$files - untracked" >>.girt/status.txt
    elif (! test -f .girt/repository/$count/$files)
    then
        if (! cmp $files .girt/index/$files) > /dev/null 2>&1
        then
            echo "$files - added to index, file changed" >>.girt/status.txt
        else
            echo "$files - added to index" >>.girt/status.txt
        fi
    elif (! cmp .girt/index/$files .girt/repository/$count/$files) > /dev/null 2>&1
    then
        if (! cmp $files .girt/index/$files) > /dev/null 2>&1
        then
            echo "$files - file changed, different changes staged for commit" >>.girt/status.txt
        else
            echo "$files - file changed, changes staged for commit" >>.girt/status.txt
        fi
    elif (! cmp $files .girt/index/$files) > /dev/null 2>&1
    then
        echo "$files - file changed, changes not staged for commit" >>.girt/status.txt
    else
        echo "$files - same as repo" >>.girt/status.txt
    fi
done
# get status of all files in repository but not in current directory
deleted=$(find ".girt/repository/$count/" "." "." -printf '%P\n' | sort | uniq -u)
for files in $deleted
do
    if (test -f .girt/index/$files)
    then
        if (! cmp .girt/index/$files .girt/repository/$count/$files) > /dev/null 2>&1
        then
            echo "$files - file deleted, different changes staged for commit" >>.girt/status.txt
        else
            echo "$files - file deleted" >>.girt/status.txt
        fi
    else
        echo "$files - deleted" >>.girt/status.txt
    fi
done
# get status of all files in index but not in current directory
deleted=$(find ".girt/index/" "." "." -printf '%P\n' | sort | uniq -u)
for files in $deleted
do
    file=$(echo $files | sed "s/.girt\/index\///")
    if (! test -f .girt/repository/$count/$file)
    then
        echo "$file - added to index, file deleted" >>.girt/status.txt
    fi
done
# prints status
cat ".girt/status.txt" | sort