#!/bin/dash
# outputs error message if .girt was not initiated
if (! test -d .girt)
then
    echo "girt-add: error: girt repository directory .girt not found"
    exit 1
fi
# adds files to index
for files in $@
do
    # ensures file name is valid
    if (! test $(echo $files | grep -e '^[a-zA-Z0-9][a-zA-Z0-9_.-]*$')) 
    then
        echo "girt-add: error: invalid filename '$files'"
    elif (test -f $files) 
    then
        cp $files .girt/index/$files
    elif (test -f .girt/index/$files)
    then
        # special scenario where the file in current directory was deleted but is still in index
        rm .girt/index/$files
    else
        # file is not in directory
        echo "girt-add: error: can not open '$files'"
        exit 1
    fi
done